version: '3'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/answersai
      - JWT_SECRET=@ssw0rd!s3cur3R@nd0mS3cr3tG3n3r@t3d!
      - API_SECRET=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
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.29
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
